services:
  - type: web
    name: place-reviews-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate &&
      gunicorn place_reviews.wsgi:application
